### ISSUE TITLE
billing class column

### ISSUE THREAD

**Issue by Causink11** [CMSgov/hospital-price-transparency#134]
Is the billing_class field not required for 2025? It is erroring out on validation?

**Comment by RidenourK** [comment]
@Causink11. Thank you for your question. 

As indicated in the “Documentation” section of CMS Hospital Price Transparency - Data Dictionary GitHub repository, “billing_class” is an optional data element. It is not required to be included, but instructions have been added to support standardization of disclosure of this data element for hospitals that wish to provide more contextual information about their charges. If the billing_class header is included in the MRF, we recommend it be included on the third row.

Would you be willing to provide a screenshot of the error you are receiving and a sample of the MRF that is triggering this error to the CMS HPT mailbox at [PriceTransparencyHospitalCharges@cms.hhs.gov](mailto:PriceTransparencyHospitalCharges@cms.hhs.gov) so we may investigate this further?
